<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '9b38cf48e83f5d8f60375221cd213eee' => $vendorDir . '/phpstan/phpstan/bootstrap.php',
    'c14057a02afc95b84dc5bf85d98c5b66' => $vendorDir . '/julien731/wp-dismissible-notices-handler/handler.php',
    'ff8834a662873e3e689a4283b27598d2' => $vendorDir . '/julien731/wp-dismissible-notices-handler/includes/helper-functions.php',
    '0d59ee240a4cd96ddbb4ff164fccea4d' => $vendorDir . '/symfony/polyfill-php73/bootstrap.php',
    'a2c48002d05f7782d8b603bd2bcb5252' => $vendorDir . '/johnbillion/extended-cpts/extended-cpts.php',
    'a50f2d2ba04e0c6b552331bf2bdeba41' => $vendorDir . '/julien731/wp-review-me/review.php',
    'e67733b1c67d30ae0534fc358ce6ccd9' => $vendorDir . '/wp-cache-remember/wp-cache-remember.php',
    '33463dafc79559dfcabd4bb559eb4b57' => $vendorDir . '/wpbp/cpt_columns/CPT_Columns.php',
    'ab9c306a707f0fda77eaa634dc02fca6' => $vendorDir . '/wpbp/cronplus/cronplus.php',
    '1ed2e86416e62cbd8a94629858dae65f' => $vendorDir . '/wpbp/debug/debug.php',
    '9b6589aa6a8382a7459438252aee60ae' => $vendorDir . '/wpbp/fakepage/fake-page.php',
    '5883ee4b643b7e87de56323bec06b24c' => $vendorDir . '/wpbp/language/language.php',
    '174f5545298fc44fc2ee140f23d4bfef' => $vendorDir . '/wpbp/pointerplus/pointerplus.php',
    '1fa8862ea6a31004f198b1e9b7b6b499' => $vendorDir . '/wpbp/template/template.php',
    'e7a23b473708f4b0fb5b99fe921bee83' => $vendorDir . '/wpbp/widgets-helper/wph-widget.php',
    '0509b34a4bd7aebefeac629c9dc8a978' => $vendorDir . '/wpdesk/wp-notice/src/WPDesk/notice-functions.php',
    '241d2b5b9c1e680c0770b006b0271156' => $vendorDir . '/yahnis-elsts/plugin-update-checker/load-v4p9.php',
    '2d130972ab3066918649e0c2c9109d03' => $vendorDir . '/wp-custom-bulk-actions/custom-bulk-actions.php',
);
