<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WPDesk\\PluginBuilder\\' => array($vendorDir . '/wpdesk/wp-builder/src'),
    'WPDesk\\Notice\\' => array($vendorDir . '/wpdesk/wp-notice/src/WPDesk/Notice'),
    'Symfony\\Polyfill\\Php73\\' => array($vendorDir . '/symfony/polyfill-php73'),
    'PHPStan\\WordPress\\' => array($vendorDir . '/szepeviktor/phpstan-wordpress/src'),
    'Micropackage\\Requirements\\' => array($vendorDir . '/micropackage/requirements/src'),
    'Micropackage\\Internationalization\\' => array($vendorDir . '/micropackage/internationalization/src'),
    'ExtCPTs\\Tests\\' => array($vendorDir . '/johnbillion/extended-cpts/tests/phpunit'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'Coachs\\Internals\\' => array($baseDir . '/internals'),
    'Coachs\\Integrations\\' => array($baseDir . '/integrations'),
    'Coachs\\Frontend\\' => array($baseDir . '/frontend'),
    'Coachs\\Engine\\' => array($baseDir . '/engine'),
    'Coachs\\Backend\\' => array($baseDir . '/backend'),
    'Coachs\\Ajax\\' => array($baseDir . '/ajax'),
);
